#!/bin/bash

# We need 3 directories for Obiwan
export zpts_code=$CSCRATCH/zpts_code
export zpts_out=$CSCRATCH/zpts_out

# Python environment, Ted Kisner's desiconda for imaging  
module use $zpts_code/legacyzpts/etc/modulefiles

# Obiwan and imaging pipeline repos
export PYTHONPATH=$obiwan_code/legacypipe/py:${PYTHONPATH}
export PYTHONPATH=$obiwan_code/legacyzpts/py:${PYTHONPATH}

# QDO (for Obiwan production runs)
export QDO_BATCH_PROFILE=$NERSC_HOST
export QDO_BACKEND=postgres
export QDO_DB_NAME=desirun
export QDO_DB_HOST=scidb2.nersc.gov
export QDO_DB_USER=desirun_admin
# directory from "which qdo" but without the trailing /bin/qdo, eg which qdo should give
export QDO_DIR=$CSCRATCH/obiwan_desiconda_add_pytest/conda
# get db pass
export QDO_DB_PASS="$(cat $HOME/.qdo_db_pass)"
